services:
  - type: web
    name: communitycare-app
    env: python
    plan: free
    region: oregon  # or your preferred region
    buildCommand: |
      pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: communitycare-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.4

databases:
  - name: communitycare-db
    plan: free
    databaseName: communitycare
    user: communitycare_user